# Generated by Django 2.2.6 on 2019-11-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techType', models.CharField(max_length=200)),
                ('annualPay', models.CharField(max_length=200)),
                ('recruitGroup', models.CharField(max_length=200)),
                ('candidateCriteria', models.CharField(max_length=200)),
                ('recruitDescription', models.CharField(max_length=200)),
            ],
        ),
    ]
